NUMBER_OF_DECKS = 1
NUMBER_OF_PLAYERS = 4
NUMBER_OF_INITIAL_CARDS = 7

NUMBER_OF_THREADS = 1   # to be implemented
NUMBER_OF_SIMULATIONS_PER_THREAD = 10   # type 0 to make it endless

PLAYER_ID = 900

# Rules
ONLY_ONE_PLAYER_CAN_WIN = False